Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2023-12, with the labels that each got.

#139 fix(popup): 修复destroy-on-close无效
  example/src/App.vue
  example/src/pages/demo/basic/popup/index.vue
  example/src/store/modules/app/index.ts
  packages/nutui/components/overlay/overlay.ts
  packages/nutui/components/overlay/overlay.vue
  packages/nutui/components/popup/popup.vue
  packages/nutui/components/popup/use-popup.ts
  packages/nutui/components/transition/transition.ts
  packages/nutui/components/transition/transition.vue
  packages/nutui/components/transition/use-transition.ts
Labels: size/M

#140 fix(menu): 修复menu闪屏动画错误以及位置偏移
  packages/nutui/components/menu/menu.vue
  packages/nutui/components/menuitem/index.scss
  packages/nutui/components/menuitem/menuitem.vue
Labels: size/M

#141 feat(safearea): 新增SafeArea组件
  docs/.vitepress/items.ts
  docs/components/layout/safearea.md
  example/config.ts
  example/src/pages/demo/layout/safearea/index.vue
  packages/nutui/components/index.ts
  packages/nutui/components/safearea/index.scss
  packages/nutui/components/safearea/index.ts
  packages/nutui/components/safearea/safearea.ts
  packages/nutui/components/safearea/safearea.vue
Labels: size/L

#146 fix(navbar): 修复标题居中等样式问题
  docs/components/nav/navbar.md
  example/src/pages/demo/nav/navbar/index.vue
  packages/nutui/components/navbar/index.scss
Labels: size/L

#145 fix(sku): 修复小程序下选项内容的滚动问题
  packages/nutui/components/sku/sku.vue
Labels: size/XS

#144 fix(tabs): 修复嵌套使用时的样式错乱问题
  .stylelintrc
  example/src/pages/demo/nav/tabs/index.vue
  packages/nutui/components/tabs/index.scss
  packages/nutui/components/tabs/tabs.vue
Labels: size/L

#143 feat(radio): 组件设置 button 形状时支持改变大小
  docs/components/dentry/radio.md
  example/src/pages/demo/dentry/radio/index.vue
  packages/nutui/components/radio/index.scss
  packages/nutui/components/radio/radio.ts
  packages/nutui/components/radio/radio.vue
Labels: size/M

#149 fix(textarea): 启用autosize时readonly样式不统一；fix(transition): 组件无法正常关闭；
  packages/nutui/components/popup/popup.vue
  packages/nutui/components/popup/use-popup.ts
  packages/nutui/components/textarea/index.scss
  packages/nutui/components/textarea/textarea.vue
  packages/nutui/components/transition/index.scss
  packages/nutui/components/transition/transition.vue
  packages/nutui/components/transition/use-transition.ts
Labels: size/M
