Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-08, with the labels that each got.

#384 feat(cell): 新增icon、clickable属性
  docs/components/basic/cell.md
  example/src/pages/demo/basic/cell/index.vue
  packages/nutui/components/cell/cell.ts
  packages/nutui/components/cell/cell.vue
  packages/nutui/components/cell/index.scss
  packages/nutui/components/cell/index.ts
  packages/nutui/components/cellgroup/cellgroup.ts
  packages/nutui/components/cellgroup/cellgroup.vue
  packages/nutui/components/cellgroup/index.scss
  packages/nutui/components/cellgroup/index.ts
Labels: size/L

#385 feat(checkbox): 新增checked-value、unchecked-value属性
  docs/components/dentry/checkbox.md
  example/src/pages/demo/dentry/checkbox/index.vue
  packages/nutui/components/checkbox/checkbox.ts
  packages/nutui/components/checkbox/checkbox.vue
  packages/nutui/components/checkbox/index.scss
  packages/nutui/components/checkboxgroup/checkboxgroup.ts
  packages/nutui/components/checkboxgroup/checkboxgroup.vue
  packages/nutui/components/checkboxgroup/index.ts
  packages/nutui/components/checkboxgroup/types.ts
  packages/nutui/components/form/form.ts
  packages/nutui/components/input/input.ts
  packages/nutui/components/inputnumber/inputnumber.ts
  packages/nutui/components/radio/radio.ts
  packages/nutui/components/range/range.ts
  packages/nutui/components/rate/rate.ts
  packages/nutui/components/searchbar/searchbar.ts
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/uploader/uploader.ts
Labels: size/XXL

#386 docs(overlay): 修复示例z-index表现异常
  docs/components/basic/overlay.md
  example/src/pages/demo/basic/overlay/index.vue
  packages/nutui/components/overlay/index.ts
  packages/nutui/components/overlay/overlay.vue
Labels: size/L

#387 fix(range): 修复点击控制导致NaN问题
  packages/nutui/components/range/index.scss
  packages/nutui/components/range/index.ts
  packages/nutui/components/range/range.ts
  packages/nutui/components/range/range.vue
  packages/nutui/components/range/types.ts
Labels: size/L

#388 fix(range): 修复可能存在flex-shrink为0时的样式异常
  packages/nutui/components/range/index.scss
Labels: size/XS

#389 feat(form): 为form组件的validate方法的返回添加类型声明
  docs/components/dentry/form.md
  example/src/manifest.json
  example/src/pages/demo/dentry/form/index.vue
  packages/nutui/components/form/form.vue
  packages/nutui/components/form/types.ts
  packages/nutui/components/invoice/invoice.vue
Labels: size/M

#393 fix(short-password): 修复忘记密码文本对齐问题
  example/src/pages/demo/dentry/shortpassword/index.vue
  packages/nutui/components/shortpassword/index.scss
  packages/nutui/components/shortpassword/shortpassword.vue
Labels: size/L

#394 docs: 新增uniapp内置组件类型提示说明
  docs/guide/quick-start.md
Labels: size/XS

#395 chore(sidenavbar): fix demo popup z-index prop warning
  example/src/pages/demo/nav/sidenavbar/index.vue
Labels: size/XS

#391 refactor: defineOptions instead of two script once more
  docs/guide/quick-start.md
  example/src/pages/demo/basic/configprovider/index.vue
  example/src/pages/demo/business/address/index.vue
  example/src/pages/demo/business/sku/index.vue
  example/src/pages/demo/dentry/calendar/index.vue
  example/src/pages/demo/exhibition/list/index.vue
  example/src/pages/demo/nav/sidenavbar/index.vue
  packages/nutui/components/actionsheet/actionsheet.vue
  packages/nutui/components/address/address.vue
  packages/nutui/components/countup/countup.vue
  packages/nutui/components/ellipsis/ellipsis.vue
  packages/nutui/components/hiteggs/hiteggs.vue
  packages/nutui/components/noticebar/noticebar.vue
  packages/nutui/components/rate/index.scss
  packages/nutui/components/rate/rate.vue
  packages/nutui/components/row/index.scss
  packages/nutui/components/row/row.vue
  packages/nutui/components/safearea/safearea.vue
  packages/nutui/components/searchbar/index.ts
  packages/nutui/components/searchbar/searchbar.ts
  packages/nutui/components/searchbar/searchbar.vue
  packages/nutui/components/searchbar/types.ts
  packages/nutui/components/shakedice/index.scss
  packages/nutui/components/shakedice/index.ts
  packages/nutui/components/shakedice/shakedice.ts
  packages/nutui/components/shakedice/shakedice.vue
  packages/nutui/components/shakedice/types.ts
  packages/nutui/components/shortpassword/index.scss
  packages/nutui/components/shortpassword/shortpassword.vue
  packages/nutui/components/sidenavbar/sidenavbar.ts
  packages/nutui/components/sidenavbar/sidenavbar.vue
  packages/nutui/components/sidenavbaritem/sidenavbaritem.ts
  packages/nutui/components/sidenavbaritem/sidenavbaritem.vue
  packages/nutui/components/signature/index.ts
  packages/nutui/components/signature/signature.vue
  packages/nutui/components/signature/use-signature.ts
  packages/nutui/components/skeleton/index.scss
  packages/nutui/components/skeleton/index.ts
  packages/nutui/components/skeleton/skeleton.vue
  packages/nutui/components/subsidenavbar/subsidenavbar.ts
  packages/nutui/components/subsidenavbar/subsidenavbar.vue
  packages/nutui/locale/locale.ts
Labels: size/XXL

#398 docs: 修改uni-app-types文档地址
  docs/guide/quick-start.md
Labels: size/XS

#399 chore: update stylelint shorthands rule
  .stylelintrc
Labels: size/XS

#397 适配2021年前的旧机型
  packages/nutui/components/shortpassword/index.scss
Labels: size/XS

#396 适配2021年前的旧机型
  packages/nutui/components/numberkeyboard/index.scss
Labels: size/S

#400 fix: 修复部分机型不支持css inset
  packages/nutui/components/addresslist/compoents/generalshell.vue
  packages/nutui/components/addresslist/index.scss
  packages/nutui/components/animate/index.scss
  packages/nutui/components/calendaritem/index.scss
  packages/nutui/components/category/index.scss
  packages/nutui/components/categorypane/index.scss
  packages/nutui/components/checkbox/index.scss
  packages/nutui/components/collapseitem/index.scss
  packages/nutui/components/comment/components/CmtBottom.vue
  packages/nutui/components/comment/components/CmtImages.vue
  packages/nutui/components/countup/index.scss
  packages/nutui/components/divider/index.scss
  packages/nutui/components/elevator/index.scss
  packages/nutui/components/formitem/index.scss
  packages/nutui/components/griditem/index.scss
  packages/nutui/components/overlay/index.scss
  packages/nutui/components/progress/index.scss
  packages/nutui/components/radio/index.scss
  packages/nutui/components/range/index.scss
  packages/nutui/components/row/index.scss
  packages/nutui/components/skuselect/skuselect.vue
  packages/nutui/components/step/index.scss
  packages/nutui/components/tabs/index.scss
  packages/nutui/components/timedetail/index.scss
  packages/nutui/components/watermark/index.scss
Labels: size/L

#402 fix(sticky): 修复降级为fixed实现时效果异常
  docs/components/layout/sticky.md
  example/src/pages/demo/layout/sticky/index.vue
  packages/nutui/components/sticky/index.scss
  packages/nutui/components/sticky/sticky.ts
  packages/nutui/components/sticky/sticky.vue
Labels: size/L

#403 docs(swipe): 更新实例方法文档描述
  docs/components/feedback/swipe.md
  packages/nutui/components/swipe/index.ts
  packages/nutui/components/swipe/swipe.ts
  packages/nutui/components/swipe/swipe.vue
  packages/nutui/components/swipe/types.ts
  packages/nutui/components/swipegroup/swipegroup.vue
Labels: size/L

#407 fix: update type declaration from '@vue/runtime-core' to 'vue' for Vu…
  packages/nutui/global.d.ts
Labels: size/S

#409 chore(input-number): fix scss warning
  packages/nutui/components/inputnumber/index.scss
Labels: size/XS

#412 chore: update deps and code style
  .gitignore
  .npmrc
  .stylelintignore
  .stylelintrc
  .vscode/extensions.json
  .vscode/settings.json
  docs/.gitignore
  docs/auto-imports.d.ts
  docs/package.json
  docs/tsconfig.json
  docs/uno.config.ts
  example/.gitignore
  example/eslint.config.js
  example/index.html
  example/manifest.config.ts
  example/package.json
  example/pages.config.ts
  example/src/main.ts
  example/tsconfig.json
  example/uno.config.ts
  example/vite.config.ts
  package.json
  packages/nutui/.gitignore
  packages/nutui/build.config.ts
  packages/nutui/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/build.ts
  scripts/publish.ts
  scripts/uni.ts
Labels: size/XXL

#413 fix(popover,shakedice,tour): fix scss warning
  packages/nutui/components/popover/index.scss
  packages/nutui/components/shakedice/index.scss
  packages/nutui/components/tour/index.scss
Labels: size/L
