Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-01, with the labels that each got.

#151 feat(watermark): 支持多行文字水印
  docs/components/exhibition/watermark.md
  example/src/pages/demo/exhibition/watermark/index.vue
  packages/nutui/components/watermark/watermark.ts
  packages/nutui/components/watermark/watermark.vue
Labels: size/M

#154 fix(calendar): 日历组件在微信小程序弹窗展示时，无法滚动到默认日期；fix(calendar): 日历组件在微信小程序中无法显示今天标记
  packages/nutui/components/calendar/calendar.vue
  packages/nutui/components/calendaritem/calendaritem.vue
Labels: size/S

#156 perf(input): 使用computed代替函数调用
  packages/nutui/components/input/input.vue
Labels: size/M

#157 feat(card): 商品卡片组件增加shopName插槽，用于店铺名称自定义
  packages/nutui/components/card/card.vue
Labels: size/XS

#162 fix(categorypane): 商品分类面板组件默认插槽不生效
  packages/nutui/components/categorypane/categorypane.vue
Labels: size/XS

#172 feat: 改进WebStorm和其他JetBrains IDE的开发体验
  .gitignore
  docs/components/basic/button.md
  docs/components/bingo/dollmachine.md
  docs/components/bingo/giftbox.md
  docs/components/bingo/marquee.md
  docs/components/bingo/turntable.md
  docs/components/business/timeselect.md
  docs/components/feedback/toast.md
  docs/components/layout/safearea.md
  package.json
  packages/nutui/package.json
  pnpm-lock.yaml
  scripts/web-types.ts
Labels: size/XXL

#174 feat(button): 新增hover-class相关属性
  docs/components/basic/button.md
  packages/nutui/components/button/button.ts
  packages/nutui/components/button/button.vue
  packages/nutui/components/button/index.scss
Labels: size/L

#175 fix(navbar): 修复zIndex无效问题
  packages/nutui/components/navbar/navbar.vue
Labels: size/XS
