Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-04, with the labels that each got.

#272 fix(picker): 修复非H5平台mask缺失
  packages/nutui/components/picker/index.scss
Labels: size/S

#273 feat(calendar): 添加calendar组件点击遮罩关闭事件和点击关闭图标事件
  docs/components/dentry/calendar.md
  packages/nutui/components/calendar/calendar.ts
  packages/nutui/components/calendar/calendar.vue
Labels: size/S

#274 feat(addresslist): 新增是否使用插槽相关属性
  docs/components/business/addresslist.md
  example/src/pages/demo/business/addresslist/index.vue
  packages/nutui/components/addresslist/addresslist.ts
  packages/nutui/components/addresslist/addresslist.vue
  packages/nutui/components/addresslist/compoents/Itemcontents.vue
  packages/nutui/components/addresslist/compoents/generalshell.vue
  packages/nutui/components/addresslist/index.scss
Labels: size/XL

#275 refactor(addresslist): 变更slot判断方式
  docs/components/business/addresslist.md
  example/src/pages/demo/business/addresslist/index.vue
  packages/nutui/components/addresslist/addresslist.ts
  packages/nutui/components/addresslist/addresslist.vue
  packages/nutui/components/addresslist/index.ts
  packages/nutui/components/addresslist/type.ts
Labels: size/L

#276 style: 统一部分组件导出行为
  packages/nutui/components/addresslist/index.ts
  packages/nutui/components/avatar/avatar.vue
  packages/nutui/components/avatar/index.ts
  packages/nutui/components/avatargroup/avatargroup.ts
  packages/nutui/components/avatargroup/avatargroup.vue
  packages/nutui/components/button/button.ts
  packages/nutui/components/button/index.ts
  packages/nutui/components/input/index.ts
  packages/nutui/components/input/input.ts
  packages/nutui/components/textarea/index.ts
  packages/nutui/components/toast/index.ts
  packages/nutui/components/toast/toast.ts
  packages/nutui/components/toast/toast.vue
  packages/nutui/components/toast/type.ts
  packages/nutui/components/toast/use-toast.ts
Labels: size/M

#279 fix(input): 修复H5环境下type为number无效
  docs/components/dentry/input.md
  packages/nutui/components/input/input.vue
  packages/nutui/components/input/type.ts
Labels: size/L

#282 fix(searchbar): 修复app端输入框对齐问题
  docs/components/dentry/searchbar.md
  example/src/pages/demo/dentry/searchbar/index.vue
  packages/nutui/components/input/input.vue
  packages/nutui/components/searchbar/index.scss
  packages/nutui/components/searchbar/index.ts
  packages/nutui/components/searchbar/searchbar.ts
  packages/nutui/components/searchbar/searchbar.vue
  packages/nutui/components/searchbar/type.ts
  packages/nutui/components/textarea/textarea.vue
  packages/nutui/styles/variables.scss
Labels: size/XL

#284 fix(swipe): 修复组件宽度超出范围以及点击关闭问题
  docs/components/feedback/swipe.md
  example/src/pages/demo/feedback/swipe/index.vue
  packages/nutui/components/swipe/index.scss
  packages/nutui/components/swipe/index.ts
  packages/nutui/components/swipe/swipe.ts
  packages/nutui/components/swipe/swipe.vue
  packages/nutui/components/swipe/type.ts
  packages/nutui/components/swipegroup/index.ts
  packages/nutui/components/swipegroup/swipegroup.vue
Labels: size/XL

#289 feat(datepicker): 事件新增date参数
  docs/components/dentry/datepicker.md
  docs/components/dentry/picker.md
  docs/components/dentry/searchbar.md
  example/src/pages/demo/dentry/datepicker/index.vue
  example/src/pages/demo/dentry/picker/index.vue
  packages/nutui/components/datepicker/datepicker.ts
  packages/nutui/components/datepicker/datepicker.vue
  packages/nutui/components/datepicker/index.scss
  packages/nutui/components/datepicker/index.ts
  packages/nutui/components/datepicker/type.ts
  packages/nutui/components/picker/index.scss
  packages/nutui/components/picker/index.ts
  packages/nutui/components/picker/picker.ts
  packages/nutui/components/picker/picker.vue
  packages/nutui/components/picker/type.ts
  packages/nutui/components/picker/use-picker.ts
  packages/nutui/components/pickercolumn/index.scss
  packages/nutui/components/pickercolumn/index.ts
  packages/nutui/components/pickercolumn/pickercolumn.ts
  packages/nutui/components/pickercolumn/pickercolumn.vue
  packages/nutui/components/pickercolumn/type.ts
Labels: size/XXL

#291 fix(ecard): 修复输入框表现异常
  docs/components/business/ecard.md
  example/src/pages/demo/business/ecard/index.vue
  packages/nutui/components/ecard/ecard.ts
  packages/nutui/components/ecard/ecard.vue
  packages/nutui/components/ecard/index.scss
  packages/nutui/components/ecard/index.ts
  packages/nutui/components/ecard/type.ts
Labels: size/XL

#292 chore: 更新peerDependencies
  packages/nutui/package.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/L

#293 feat(tag): 新增disbaled、close-icon-size属性
  docs/components/exhibition/tag.md
  example/src/pages/demo/exhibition/tag/index.vue
  packages/nutui/components/tag/index.scss
  packages/nutui/components/tag/index.ts
  packages/nutui/components/tag/tag.ts
  packages/nutui/components/tag/tag.vue
  packages/nutui/components/tag/type.ts
  packages/nutui/styles/variables.scss
Labels: size/L

#297 refactor(tag): 重构标签样式实现
  docs/components/exhibition/tag.md
  packages/nutui/components/tag/index.scss
  packages/nutui/components/tag/tag.vue
  packages/nutui/styles/variables.scss
Labels: size/L

#294 feat: 完善cell组件 to 属性
  docs/components/basic/cell.md
  example/src/auto-imports.d.ts
  packages/nutui/components/cell/cell.vue
Labels: size/L

#299 feat(switch): add disabled prop & mark disable deprecated
  docs/components/feedback/switch.md
  packages/nutui/components/switch/index.scss
  packages/nutui/components/switch/switch.ts
  packages/nutui/components/switch/switch.vue
Labels: size/S

#300 fix: 修改tabs选项卡微笑曲线属性，在navbar组件content slot中样式出错bug
  packages/nutui/components/tabs/index.scss
Labels: size/XS

#301 fix(address): 修复在选择地址后，下一级地址无法滚动到顶部
  packages/nutui/components/address/address.vue
Labels: size/S

#305 feat(sku): 新增重置商品数量方法
  docs/components/business/sku.md
  example/src/pages/demo/business/sku/index.vue
  packages/nutui/components/sku/sku.vue
  packages/nutui/components/skustepper/skustepper.vue
Labels: size/L

#307 fix: 修复useSelectorQuery在app-plus环境获取instance报错
  packages/nutui/components/_hooks/useSelectorQuery.ts
Labels: size/XS
