Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-03, with the labels that each got.

#212 修复leaf等于false并且children为空时可以选择成功的问题
  docs/components/dentry/cascader.md
  example/src/pages/demo/dentry/cascader/index.vue
  packages/nutui/components/cascader/tree.ts
Labels: size/M

#213 fix(avatar): 修复size、shape无效以及无法正确从group继承
  docs/components/exhibition/avatar.md
  packages/nutui/components/avatar/avatar.ts
  packages/nutui/components/avatar/avatar.vue
  packages/nutui/components/avatar/index.scss
  packages/nutui/components/avatar/type.ts
  packages/nutui/components/avatargroup/avatargroup.ts
  packages/nutui/components/avatargroup/avatargroup.vue
  packages/nutui/components/avatargroup/index.scss
Labels: size/L

#215 fix(avatar-group): 修复z-index无效
  packages/nutui/components/avatar/avatar.vue
Labels: size/S

#217 feat(uploader): 新增accept配置
  docs/components/dentry/uploader.md
  example/src/pages/demo/dentry/uploader/index.vue
  packages/nutui/components/uploader/uploader.vue
  packages/nutui/components/uploader/use-uploader.ts
Labels: size/L

#219 fix(textarea): 修复类型导出缺失
  packages/nutui/components/textarea/index.ts
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
  packages/nutui/components/textarea/type.ts
Labels: size/S

#221 style(input): 规范代码格式
  packages/nutui/components/input/index.scss
  packages/nutui/components/input/input.vue
  packages/nutui/components/input/type.ts
Labels: size/L

#222 style(textarea): 代码格式对齐input
  packages/nutui/components/input/input.vue
  packages/nutui/components/textarea/index.scss
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
Labels: size/L

#224 feat(textarea): 新增input事件
  docs/components/dentry/textarea.md
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
Labels: size/S

#225 fix(input,textarea): 修复input事件返回值错误
  packages/nutui/components/input/input.vue
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
Labels: size/M

#223 docs(datepicker) 补充datepicker文档
  docs/components/dentry/datepicker.md
  example/src/pages/demo/dentry/datepicker/index.vue
Labels: size/M

#233 fix(input,textarea): 新增输入框单独控制样式属性
  docs/components/dentry/input.md
  docs/components/dentry/textarea.md
  packages/nutui/components/input/input.ts
  packages/nutui/components/input/input.vue
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
Labels: size/M

#234 fix(uploader): 修复禁用时能删除文件的问题
  packages/nutui/components/uploader/uploader.vue
Labels: size/XS

#236 fix(picker): 修复微信小程序暗黑模式picker背景颜色显示错误的问题
  packages/nutui/components/picker/index.scss
  packages/nutui/components/picker/picker.vue
Labels: size/XS

#241 fix(picker): 修复ts类型错误
  packages/nutui/components/picker/picker.ts
  packages/nutui/components/picker/use-picker.ts
  packages/nutui/components/pickercolumn/types.ts
Labels: size/XS

#237 fix(elevator): 修复app端点击索引无效，并且滚动页面索引无法跟随切换问题
  packages/nutui/components/elevator/elevator.vue
Labels: size/M

#238 fix(sku): 修复默认底部按钮不显示的问题
  example/src/pages/demo/business/sku/index.vue
  packages/nutui/components/sku/sku.vue
  packages/nutui/components/skuoperate/skuoperate.vue
Labels: size/S

#240 fix(sku): 修复组件内容超出,出现横向滚动条的问题
  packages/nutui/components/sku/index.scss
  packages/nutui/components/sku/sku.vue
Labels: size/M

#245 fix(picker): 修复model-value值污染问题
  packages/nutui/components/_utils/common.ts
  packages/nutui/components/countup/countup.vue
  packages/nutui/components/datepicker/datepicker.vue
  packages/nutui/components/guessgift/guessgift.vue
  packages/nutui/components/picker/use-picker.ts
  packages/nutui/components/range/range.vue
Labels: size/L

#246 chore: 移除demo中的Locale.merge示例
  example/src/main.ts
Labels: size/XS

#247 docs(drag): 完善文档
  docs/components/feedback/drag.md
Labels: size/XS

#252 docs(toast): 添加全局调用相关说明
  docs/components/feedback/toast.md
Labels: size/M

#253 chore: 更换文档域名
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request_template.yml
  README.md
  docs/.vitepress/config.ts
  packages/nutui/README.md
Labels: size/S

#254 chore: 重新编写快速上手文档
  README.md
  docs/guide/faq.md
  docs/guide/overview.md
  docs/guide/quick-start.md
  docs/index.md
  packages/nutui/README.md
Labels: size/L

#260 feat(toast): 新增useToast控制方式
  docs/components/feedback/toast.md
  example/src/pages/demo/feedback/toast/index.vue
  packages/nutui/components/composables.ts
  packages/nutui/components/toast/index.scss
  packages/nutui/components/toast/toast.ts
  packages/nutui/components/toast/toast.vue
  packages/nutui/components/toast/types.ts
  packages/nutui/components/toast/use-toast.ts
  packages/nutui/package.json
  packages/nutui/styles/variables.scss
Labels: size/XXL

#261 docs: 新增组合式函数自动按需导入配置说明
  docs/components/feedback/toast.md
  docs/guide/quick-start.md
  example/src/pages/demo/feedback/toast/index.vue
  example/vite.config.ts
Labels: size/L

#258 fix: :bug: List 虚拟列表 listData 类型错误
  packages/nutui/components/list/list.ts
Labels: size/XS

#263 docs(toast): 新增useToast限制使用范围说明
  docs/components/feedback/toast.md
Labels: size/S

#262 refactor(drag): 重构 drag组件，修复drag组件多次拖动时位置瞬移到起始点的问题
  example/src/pages/demo/feedback/drag/index.vue
  packages/nutui/components/drag/drag.vue
  packages/nutui/components/drag/index.scss
Labels: size/L

#267 fix(dialog): 修复dialog title响应式失效的问题
  packages/nutui/components/dialog/use-dialog.ts
Labels: size/XS

#257 feat(menu, checkbox): 增强menu、checkbox组件
  example/src/pages/demo/dentry/checkbox/index.vue
  example/src/pages/demo/nav/menu/index.vue
  packages/nutui/components/checkbox/checkbox.vue
  packages/nutui/components/menu/menu.ts
  packages/nutui/components/menu/menu.vue
Labels: size/M

#270 Revert "feat(menu, checkbox): 增强menu、checkbox组件"
  example/src/pages/demo/dentry/checkbox/index.vue
  example/src/pages/demo/nav/menu/index.vue
  packages/nutui/components/checkbox/checkbox.vue
  packages/nutui/components/menu/menu.ts
  packages/nutui/components/menu/menu.vue
Labels: size/M

#269 fix: :bug: 修复Popover 气泡弹出框功能问题
  packages/nutui/components/popover/index.scss
  packages/nutui/components/popover/popover.vue
Labels: size/XS
