Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-06, with the labels that each got.

#345 fix(toast): 修复部分情况下toast的duration属性无效
  packages/nutui/components/toast/toast.vue
Labels: size/S

#347 fix(toast): 修复部分情况下toast的duration属性无效
  packages/nutui/components/toast/toast.vue
Labels: size/S

#350 docs: 完善Cascader文档示例
  docs/components/basic/transition.md
  docs/components/dentry/cascader.md
Labels: size/XS

#352 fix: 修复comment生产环境web端卡死
  example/src/pages/demo/business/comment/index.vue
  packages/nutui/components/comment/comment.vue
Labels: size/S

#354 docs: 完善Swiper文档示例
  docs/components/exhibition/swiper.md
Labels: size/XS

#360 fix(actionsheet): 修复custom-style表现异常
  docs/components/feedback/actionsheet.md
  packages/nutui/components/actionsheet/actionsheet.ts
  packages/nutui/components/actionsheet/actionsheet.vue
  packages/nutui/components/actionsheet/index.scss
  packages/nutui/components/actionsheet/index.ts
Labels: size/L
