Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-05, with the labels that each got.

#311 refactor(input)!: 重构input的dom结构
  docs/components/dentry/input.md
  example/src/pages/demo/dentry/input/index.vue
  packages/nutui/components/formitem/index.scss
  packages/nutui/components/input/index.scss
  packages/nutui/components/input/input.ts
  packages/nutui/components/input/input.vue
  packages/nutui/styles/variables.scss
Labels: size/XL

#315 docs: 更新示例项目vue版本
  docs/auto-imports.d.ts
  docs/package.json
  example/package.json
  package.json
  packages/nutui/tsconfig.json
  pnpm-lock.yaml
  scripts/package.json
Labels: size/XXL

#323 feat(menuitem): 新增item-click事件
  docs/components/nav/menu.md
  packages/nutui/components/menuitem/menuitem.ts
  packages/nutui/components/menuitem/menuitem.vue
Labels: size/L

#324 修复 在Android14微信小程序中，input focus后点击清除，值实际未清除的问题
  packages/nutui/components/input/input.vue
Labels: size/XS

#325 使用innerValue.value的值代替blur事件返回的值
  packages/nutui/components/input/input.vue
Labels: size/XS

#326 feat(tab-pane): 新增padding、background样式变量
  docs/components/nav/tabs.md
  packages/nutui/components/tabpane/index.scss
  packages/nutui/styles/variables.scss
Labels: size/S

#335 ci: 添加dev、2.x分支监听
  .github/workflows/ci.yml
Labels: size/XS

#334 refactor(form): 重构form组件以支持trigger属性及嵌套布局
  docs/components/dentry/form.md
  example/package.json
  example/src/pages/demo/dentry/form/index.vue
  example/src/pages/demo/feedback/toast/index.vue
  example/vite.config.ts
  packages/nutui/components/_plugins/lodash.ts
  packages/nutui/components/_types/base.ts
  packages/nutui/components/_types/index.ts
  packages/nutui/components/_types/path.ts
  packages/nutui/components/_types/vue.ts
  packages/nutui/components/checkbox/checkbox.ts
  packages/nutui/components/checkbox/checkbox.vue
  packages/nutui/components/checkboxgroup/checkboxgroup.vue
  packages/nutui/components/composables.ts
  packages/nutui/components/form/form.ts
  packages/nutui/components/form/form.vue
  packages/nutui/components/form/index.scss
  packages/nutui/components/form/index.ts
  packages/nutui/components/form/type.ts
  packages/nutui/components/form/types.ts
  packages/nutui/components/formitem/formitem.ts
  packages/nutui/components/formitem/formitem.vue
  packages/nutui/components/formitem/index.scss
  packages/nutui/components/formitem/index.ts
  packages/nutui/components/formitem/type.ts
  packages/nutui/components/formitem/types.ts
  packages/nutui/components/input/input.ts
  packages/nutui/components/input/input.vue
  packages/nutui/components/inputnumber/inputnumber.ts
  packages/nutui/components/inputnumber/inputnumber.vue
  packages/nutui/components/invoice/invoice.ts
  packages/nutui/components/invoice/invoice.vue
  packages/nutui/components/radio/radio.ts
  packages/nutui/components/radio/radio.vue
  packages/nutui/components/radiogroup/radiogroup.vue
  packages/nutui/components/range/range.ts
  packages/nutui/components/range/range.vue
  packages/nutui/components/rate/rate.ts
  packages/nutui/components/rate/rate.vue
  packages/nutui/components/searchbar/searchbar.ts
  packages/nutui/components/searchbar/searchbar.vue
  packages/nutui/components/switch/switch.ts
  packages/nutui/components/switch/switch.vue
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
  packages/nutui/components/uploader/uploader.ts
  packages/nutui/components/uploader/uploader.vue
  packages/nutui/locale/lang/baseLang.ts
  packages/nutui/locale/lang/en-US.ts
  packages/nutui/locale/lang/id-ID.ts
  packages/nutui/locale/lang/zh-CN.ts
  packages/nutui/locale/lang/zh-TW.ts
  packages/nutui/package.json
  pnpm-lock.yaml
Labels: size/XXL

#336 ci: 添加dev、2.x分支监听
  .github/workflows/ci.yml
Labels: size/XS

#337 feat(form): 自定义validator支持返回Error
  docs/components/dentry/form.md
  example/src/pages/demo/dentry/form/index.vue
  packages/nutui/components/formitem/formitem.vue
  packages/nutui/components/formitem/type.ts
Labels: size/L

#338 feat(form): 新增校验状态
  packages/nutui/components/formitem/formitem.vue
  packages/nutui/components/formitem/index.scss
  packages/nutui/components/formitem/type.ts
Labels: size/M
