Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-02, with the labels that each got.

#176 table props 类型定义问题
  packages/nutui/components/table/table.ts
  packages/nutui/components/table/types.ts
Labels: size/XS

#178 feat(input): 新增input事件
  docs/components/dentry/input.md
  packages/nutui/components/input/input.ts
  packages/nutui/components/input/input.vue
Labels: size/M

#180 fix(input): 移除InputType重复类型
  packages/nutui/components/input/type.ts
Labels: size/XS

#181 docs: 添加mergeVirtualHostAttributes说明
  docs/guide/faq.md
  docs/guide/quick-start.md
  docs/guide/theme.md
Labels: size/S

#182 refactor(popover): 重构popover
  docs/.vitepress/items.ts
  docs/components/exhibition/popover.md
  example/config.ts
  example/manifest.config.ts
  example/pages.config.ts
  example/src/components/ThemeSwitch.vue
  example/src/layouts/default.vue
  example/src/manifest.json
  example/src/pages.json
  example/src/pages/demo/exhibition/popover/index.vue
  packages/nutui/components/_constants/id.ts
  packages/nutui/components/popover/index.scss
  packages/nutui/components/popover/popover.ts
  packages/nutui/components/popover/popover.vue
  packages/nutui/components/popover/type.ts
Labels: size/L

#183 feat(marquee): 新增disabled属性
  docs/components/bingo/marquee.md
  packages/nutui/components/marquee/marquee.ts
  packages/nutui/components/marquee/marquee.vue
Labels: size/S

#184 feat(form): 新增 disabled 属性,支持禁用 form 下全部数据录入组件
  docs/components/dentry/form.md
  packages/nutui/components/_hooks/index.ts
  packages/nutui/components/_hooks/useChildren.ts
  packages/nutui/components/_hooks/useParent.ts
  packages/nutui/components/_hooks/useProvide.ts
  packages/nutui/components/checkbox/checkbox.ts
  packages/nutui/components/checkbox/checkbox.vue
  packages/nutui/components/checkboxgroup/checkboxgroup.vue
  packages/nutui/components/form/form.ts
  packages/nutui/components/form/form.vue
  packages/nutui/components/formitem/formitem.vue
  packages/nutui/components/input/input.vue
  packages/nutui/components/inputnumber/inputnumber.vue
  packages/nutui/components/menu/menu.vue
  packages/nutui/components/menuitem/menuitem.vue
  packages/nutui/components/radio/radio.ts
  packages/nutui/components/radio/radio.vue
  packages/nutui/components/radiogroup/radiogroup.vue
  packages/nutui/components/range/range.vue
  packages/nutui/components/rate/rate.vue
  packages/nutui/components/searchbar/searchbar.vue
  packages/nutui/components/switch/switch.vue
  packages/nutui/components/textarea/textarea.vue
  packages/nutui/components/uploader/uploader.vue
Labels: size/L

#185 feat(textarea): 新增placeholder-style、placeholder-class属性
  docs/components/dentry/textarea.md
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/textarea.vue
Labels: size/S

#186 fix(navbar): 修复在APP上顶部安全距离无效的问题
  docs/guide/quick-start.md
  packages/nutui/components/navbar/index.scss
  packages/nutui/components/navbar/navbar.vue
  scripts/uni.ts
Labels: size/XS

#187 fix(navbar): 修复占位元素重复计算状态栏高度的问题
  packages/nutui/components/navbar/navbar.vue
Labels: size/XS

#188 fix(tabs): align属性类型错误
  packages/nutui/components/tabs/tabs.ts
Labels: size/XS

#189 docs: overlay、tabs默认z-index错误
  docs/components/basic/overlay.md
  docs/components/nav/navbar.md
  docs/components/nav/tabs.md
Labels: size/S

#190 fix(input): 修复readonly无效
  packages/nutui/components/input/input.vue
Labels: size/XS

#193 fix(popup)!: destroy-on-close仅支持H5与微信小程序
  docs/components/basic/popup.md
  packages/nutui/components/transition/transition.vue
Labels: size/S

#194 fix(transition): app端destroyOnClose属性无效
  docs/components/basic/popup.md
  packages/nutui/components/transition/transition.vue
Labels: size/M

#197 fix(menu): 偏移位置错误, app 端v-show 无效
  packages/nutui/components/menu/menu.vue
  packages/nutui/components/menuitem/index.scss
  packages/nutui/components/menuitem/menuitem.vue
Labels: size/S

#199 refactor: nut-hidden替换v-show
  packages/nutui/components/elevator/elevator.vue
  packages/nutui/components/hiteggs/hiteggs.vue
  packages/nutui/components/input/input.vue
  packages/nutui/components/menuitem/index.scss
  packages/nutui/components/menuitem/menuitem.vue
  packages/nutui/components/noticebar/noticebar.vue
  packages/nutui/components/popover/popover.vue
  packages/nutui/components/searchbar/searchbar.vue
  packages/nutui/components/subsidenavbar/subsidenavbar.vue
  packages/nutui/components/switch/switch.vue
  packages/nutui/components/toast/toast.vue
  packages/nutui/components/toast/use-toast.ts
  packages/nutui/components/transition/index.scss
  packages/nutui/components/transition/use-transition.ts
  packages/nutui/styles/helpers.scss
  packages/nutui/styles/index.scss
Labels: size/M

#201 fix(form): 修复prop类型为数组时required校验无效的问题
  packages/nutui/components/form/form.vue
Labels: size/XS

#203 fix(textarea): 修复ConfirmType导出类型名称重复以及默认值错误
  packages/nutui/components/textarea/textarea.ts
  packages/nutui/components/textarea/type.ts
Labels: size/S

#204 refactor(input): 统一input类型命名规则
  packages/nutui/components/input/input.ts
  packages/nutui/components/input/type.ts
Labels: size/S

#205 fix(popup,menu): 修复 popup组件update:visible事件重复调用与menu 组件close 事件在小程序中无法触发
  packages/nutui/components/menuitem/menuitem.vue
  packages/nutui/components/popup/use-popup.ts
Labels: size/M

#208 fix(uploader): 修复beforeDelete默认值无效以及不支持promise
  packages/nutui/components/uploader/uploader.ts
  packages/nutui/components/uploader/uploader.vue
Labels: size/XS
