Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2024-10, with the labels that each got.

#435 fix(dialog): 修复小程序平台启用`close-on-popstate`时onMounted报错
  docs/components/feedback/dialog.md
  packages/nutui/components/dialog/use-dialog.ts
Labels: size/M

#436 fix(short-password): 修复 `close-on-click-overlay` 属性无效
  packages/nutui/components/shortpassword/shortpassword.vue
Labels: size/XS

#437 fix(popup): 修复 `visible` 初始值为 `true` 时丢失 `z-index` 问题
  packages/nutui/components/popup/use-popup.ts
Labels: size/S

#441 fix(uploader): 修复uploader组件在app端，succes事件之后还执行progress事件的问题
  packages/nutui/components/uploader/uploader.vue
Labels: size/XS

#442 fix(picker): 修复showToolbar等于false时,picker组件宽度为0不显示的问题
  packages/nutui/components/picker/index.scss
Labels: size/S

#443 fix(menu): 修复menu组件在app平台报错的问题
  packages/nutui/components/menu/menu.vue
  packages/nutui/components/menuitem/menuitem.vue
Labels: size/XS
