Repository nutui-uniapp/nutui-uniapp, pull requests merged in 2025-07, with the labels that each got.

#474 docs(category): 修改示例代码错误
  docs/components/business/category.md
Labels: size/XS

#473 fix(cascader): 修复级联选择器选中和不可选的样式层级错误
  packages/nutui/components/cascader/index.scss
Labels: size/M

#477 feat(input-number): 支持输入框类型参数
  docs/components/dentry/inputnumber.md
  packages/nutui/components/inputnumber/inputnumber.ts
  packages/nutui/components/inputnumber/inputnumber.vue
Labels: size/M

#476 fix(category): 修改div标签
  packages/nutui/components/category/category.ts
  packages/nutui/components/category/category.vue
  packages/nutui/components/category/index.scss
  packages/nutui/components/categorypane/categorypane.ts
  packages/nutui/components/categorypane/categorypane.vue
Labels: size/L
